using PDFMaster.Models;

namespace PDFMaster.Services;

public sealed class LocalizationService
{
    private static readonly Dictionary<string, string> ExtendedEnglish = new()
    {
        ["TabEditor"] = "Edit PDF",
        ["TabCompress"] = "Compress",
        ["TabMerge"] = "Merge PDF",
        ["TabTools"] = "Tools",
        ["TabPdfToWord"] = "PDF to Word",
        ["EditorHint"] = "Open a PDF to edit. Use Edit text to change existing content (click a text block). Use Select to move highlights and shapes. Save to apply changes.",
        ["EditorOpen"] = "Open PDF",
        ["EditorNewPdf"] = "New PDF",
        ["EditorNewCreated"] = "New blank PDF — {0} page(s).",
        ["EditorClose"] = "Close PDF",
        ["EditorClosed"] = "PDF closed",
        ["EditorSave"] = "Save PDF",
        ["EditorSaveAs"] = "Save as...",
        ["EditorUndo"] = "Undo",
        ["EditorRedo"] = "Redo",
        ["EditorNoDocument"] = "No PDF loaded. Click Open PDF or drop a file here.",
        ["EditorPages"] = "Pages",
        ["EditorPagesDragHint"] = "Drag pages to reorder",
        ["EditorPagePreview"] = "Page preview",
        ["EditorToolSelect"] = "Select",
        ["EditorToolEditText"] = "Edit text",
        ["EditorToolText"] = "Add text",
        ["EditorToolImage"] = "Add image",
        ["EditorToolSignature"] = "Signature",
        ["EditorToolStamp"] = "Stamp",
        ["EditorToolRectangle"] = "Rectangle",
        ["EditorToolEllipse"] = "Ellipse",
        ["EditorToolLine"] = "Line",
        ["EditorAddTextField"] = "Add text field",
        ["EditorAddComboField"] = "Add combo field",
        ["EditorFormFieldName"] = "Field name",
        ["EditorFormDefaultValue"] = "Default value",
        ["EditorComboOptions"] = "Options (one per line)",
        ["EditorTextFieldPrompt"] = "Configure the field name, text style, and default value, then draw the field on the page.",
        ["EditorComboFieldPrompt"] = "Enter the field name, options, and default value, then draw the field on the page.",
        ["EditorDrawFormFieldHint"] = "Drag on the page to draw the form field area.",
        ["EditorPendingFormFieldHint"] = "Place \"{0}\" on the page: click and drag on the PDF preview. It will appear in the list after placement.",
        ["EditorFormFontFamily"] = "Font family",
        ["EditorFormRotation"] = "Rotation",
        ["EditorFormPreview"] = "Preview",
        ["EditorFormFieldAdded"] = "Added form field: {0}",
        ["EditorColorHex"] = "Hex",
        ["EditorToolHighlight"] = "Highlight",
        ["EditorToolWhiteout"] = "Whiteout",
        ["EditorRotateLeft"] = "Rotate left",
        ["EditorRotateRight"] = "Rotate right",
        ["EditorAddPage"] = "Add page",
        ["EditorPageAdded"] = "Added blank page {0}.",
        ["EditorCannotDeleteLastPage"] = "Cannot delete the only page in the document.",
        ["EditorDeletePage"] = "Delete page",
        ["EditorMoveUp"] = "Move up",
        ["EditorMoveDown"] = "Move down",
        ["EditorZoomIn"] = "Zoom in",
        ["EditorZoomOut"] = "Zoom out",
        ["EditorTextPrompt"] = "Enter text to place on the page:",
        ["EditorAddTextPrompt"] = "Enter your text and choose font, color, and rotation, then click on the page to place it.",
        ["EditorAddTextReady"] = "Text \"{0}\" ready — click on the page to place it.",
        ["EditorAddTextPreviewDefault"] = "Sample text",
        ["EditorStampPrompt"] = "Enter stamp text (e.g. APPROVED):",
        ["EditorStampColor"] = "Stamp color",
        ["EditorStampFont"] = "Font & style",
        ["EditorStampPreview"] = "Preview",
        ["EditorStampReady"] = "Stamp \"{0}\" ready — click on the page to place it.",
        ["EditorFormFields"] = "Form fields",
        ["EditorNoFormFields"] = "No form fields in this PDF.",
        ["EditorFormValue"] = "Field value",
        ["EditorApplyFormValue"] = "Apply value",
        ["EditorSelectFormField"] = "Select a form field first.",
        ["EditorFormReadOnly"] = "That form field is read-only.",
        ["EditorFormApplied"] = "Updated form field: {0}",
        ["EditorDeleteFormField"] = "Delete field",
        ["EditorEditFormField"] = "Edit field",
        ["EditorDeleteFormFieldConfirm"] = "Delete form field \"{0}\" from this PDF?",
        ["EditorFormFieldDeleted"] = "Deleted form field: {0}",
        ["EditorImageFilter"] = "Image files|*.png;*.jpg;*.jpeg;*.bmp;*.gif;*.webp|All files|*.*",
        ["EditorOpenFilter"] = "PDF files|*.pdf|All files|*.*",
        ["EditorSaveFilter"] = "PDF files|*.pdf",
        ["EditorCompressOnSave"] = "Compress when saving",
        ["EditorLoaded"] = "Loaded {0} — {1} page(s). Click blue text boxes to edit existing content.",
        ["EditorSaved"] = "Saved to {0}",
        ["EditorSelectPage"] = "Select a page first.",
        ["EditorDeleteSelection"] = "Delete selection",
        ["EditorSelectHint"] = "Select tool: click to select, drag to move, corner handles to resize, top dot to rotate. Double-click text/stamps to edit font and style.",
        ["EditorTransformHint"] = "Drag corner handles to resize. Drag the top dot to rotate. Double-click stamp to change font, size, and style.",
        ["EditorEditTextHint"] = "Edit text: blue boxes are text, orange boxes are images/icons. Click to select, drag to move, double-click text to edit. Use the panel for font size, color, and style. Save PDF to apply.",
        ["EditorContentEditTitle"] = "Edit selection",
        ["EditorBlockText"] = "Text",
        ["EditorBlockFontSize"] = "Font size",
        ["EditorBlockColor"] = "Color",
        ["EditorContentEditHint"] = "Drag to move. Delete removes the block. Save PDF to apply.",
        ["EditorImageSelected"] = "Image or icon selected — drag to move or delete.",
        ["EditorRotateStamp"] = "Rotate stamp",
        ["EditorRotateSelection"] = "Drag to rotate",
        ["EditorPickColor"] = "Pick color...",
        ["EditorSignatureTitle"] = "Create signature",
        ["EditorSignatureDrawTab"] = "Draw",
        ["EditorSignatureTypeTab"] = "Type",
        ["EditorSignatureUploadTab"] = "Upload",
        ["EditorSignatureDrawHint"] = "Draw your signature with the mouse or pen.",
        ["EditorSignatureTypeHint"] = "Type your name, choose font, size, color, and style.",
        ["EditorSignatureUploadHint"] = "Upload an image of your signature.",
        ["EditorSignatureBrowse"] = "Browse image...",
        ["EditorSignatureClear"] = "Clear",
        ["EditorSignatureDefaultName"] = "Your name",
        ["EditorSignatureReady"] = "Signature ready — click on the page to place it.",
        ["Create"] = "Create",
        ["EditorEditTextPrompt"] = "Edit text block:",
        ["EditorFormFieldEdited"] = "Edit form field: {0}",
        ["EditorDropHint"] = "Drop a PDF file here",
        ["CompressHint"] = "Reduce PDF file size. Single file or batch folder. High/Maximum levels use Ghostscript when available.",
        ["CompressMode"] = "Mode",
        ["CompressModeSingle"] = "Single PDF",
        ["CompressModeBatch"] = "Batch folder",
        ["CompressBatchFolder"] = "Input folder (PDF files)",
        ["CompressBatchButton"] = "Compress all PDFs",
        ["CompressBatchDone"] = "Compressed {0} PDF file(s).",
        ["CompressSelectBatchFolder"] = "Please select an input folder with PDF files.",
        ["CompressGhostscriptReady"] = "Ghostscript detected — High and Maximum use stronger compression.",
        ["CompressGhostscriptMissing"] = "Ghostscript not found. Run setup-tools.bat for stronger High/Maximum compression.",
        ["CompressSource"] = "Source PDF",
        ["CompressOutput"] = "Output folder",
        ["CompressLevel"] = "Compression level",
        ["CompressLevelLow"] = "Low — fastest, smallest reduction",
        ["CompressLevelMedium"] = "Medium — balanced",
        ["CompressLevelHigh"] = "High — smaller files",
        ["CompressLevelMaximum"] = "Maximum — smallest size",
        ["CompressButton"] = "Compress PDF",
        ["CompressReady"] = "Ready",
        ["CompressProcessing"] = "Compressing...",
        ["CompressDone"] = "Done — saved {0} ({1} → {2})",
        ["CompressFailed"] = "Compression failed",
        ["CompressSelectFile"] = "Please select a PDF file.",
        ["CompressSelectOutput"] = "Please select an output folder.",
        ["MergeHint"] = "Add multiple PDF files and drag or use arrows to set merge order. The first file in the list becomes the first pages in the output.",
        ["MergeAddFiles"] = "Add PDFs",
        ["MergeRemove"] = "Remove",
        ["MergeMoveUp"] = "Move up",
        ["MergeMoveDown"] = "Move down",
        ["MergeClear"] = "Clear list",
        ["MergeOutputName"] = "Output file name",
        ["MergeOutputFolder"] = "Output folder",
        ["MergeButton"] = "Merge PDFs",
        ["MergeReady"] = "Ready",
        ["MergeProcessing"] = "Merging...",
        ["MergeDone"] = "Merged {0} file(s) → {1}",
        ["MergeFailed"] = "Merge failed",
        ["MergeNeedTwo"] = "Add at least one PDF file.",
        ["MergeSelectOutput"] = "Please select an output folder.",
        ["ToolsSource"] = "Source PDF",
        ["SplitHint"] = "Split a PDF into multiple files by page, every N pages, or at specific page numbers.",
        ["SplitMode"] = "Split mode",
        ["SplitModeEveryPage"] = "Every page → separate PDF",
        ["SplitModeEveryN"] = "Every N pages",
        ["SplitModeAtPages"] = "Split after page numbers",
        ["SplitParam"] = "Parameter",
        ["SplitParamEveryPage"] = "No parameter needed",
        ["SplitParamEveryN"] = "Pages per file, e.g. 5",
        ["SplitParamAtPages"] = "Page numbers separated by commas, e.g. 3, 7, 12",
        ["SplitButton"] = "Split PDF",
        ["SplitProcessing"] = "Splitting...",
        ["SplitDone"] = "Created {0} PDF file(s).",
        ["SplitFailed"] = "Split failed",
        ["SplitInvalidParam"] = "Invalid split parameter.",
        ["ExtractHint"] = "Extract a page range from a PDF into a new file. Use format 1-5 or a single page number.",
        ["ExtractRange"] = "Page range",
        ["ExtractOutputName"] = "Output file",
        ["ExtractButton"] = "Extract pages",
        ["ExtractProcessing"] = "Extracting...",
        ["ExtractDone"] = "Extracted to {0}",
        ["ExtractFailed"] = "Extract failed",
        ["ExtractInvalidRange"] = "Enter a valid page range (e.g. 1-5 or 3).",
        ["ExtractSelectOutput"] = "Please choose an output file.",
        ["WatermarkHint"] = "Apply a text watermark to every page of a PDF.",
        ["WatermarkText"] = "Watermark text",
        ["WatermarkDiagonal"] = "Diagonal watermark",
        ["WatermarkButton"] = "Apply watermark",
        ["WatermarkProcessing"] = "Applying watermark...",
        ["WatermarkDone"] = "Watermarked PDF saved to {0}",
        ["WatermarkFailed"] = "Watermark failed",
        ["WatermarkEnterText"] = "Enter watermark text.",
        ["ImagesToPdfHint"] = "Create a new PDF from one or more images. Each image becomes one page, scaled to fit.",
        ["ImagesToPdfSource"] = "Images",
        ["ImagesToPdfBrowse"] = "Browse images...",
        ["ImagesToPdfOutput"] = "Output PDF",
        ["ImagesToPdfButton"] = "Create PDF from images",
        ["ImagesToPdfProcessing"] = "Creating PDF from images...",
        ["ImagesToPdfDone"] = "Created PDF with {0} page(s): {1}",
        ["ImagesToPdfFailed"] = "Could not create PDF from images.",
        ["ImagesToPdfSelectImages"] = "Select at least one image file.",
        ["PdfToWordHint"] = "Convert PDF to an editable Word (.docx) file. With layout preservation, text position, spacing, font size, and images are kept as close as possible to the original. Complex designs may still differ slightly.",
        ["PdfToWordPreserveLayout"] = "Preserve layout and styling",
        ["PdfToWordOutput"] = "Output Word file",
        ["PdfToWordFilter"] = "Word documents|*.docx",
        ["PdfToWordButton"] = "Convert to Word",
        ["PdfToWordProcessing"] = "Converting to Word...",
        ["PdfToWordProgress"] = "Converting page {0}...",
        ["PdfToWordDone"] = "Converted {0} page(s) to {1}",
        ["PdfToWordFailed"] = "PDF to Word conversion failed.",
        ["PdfToWordSelectOutput"] = "Please choose an output .docx file.",
        ["ExtractRangeExample"] = "1-",
        ["About"] = "About",
        ["AboutVersion"] = "Version",
        ["AboutAuthorPrefix"] = "Copyright © 2026 ",
        ["AboutDescription"] = "Modern Windows PDF editor, compressor, merge, and tools suite.",
        ["AboutFeatures"] = "• Edit PDF — pages, text, images, signatures, forms, undo/redo\n• Compress — single or batch, Ghostscript for max quality\n• Merge — reorder PDFs before combining\n• Tools — split, extract, watermark, images to PDF\n• PDF to Word — extract text to .docx\n• Dark/light theme · 8 languages · RTL Arabic",
        ["AboutClose"] = "Close",
        ["Ok"] = "OK",
    };

    private static readonly Dictionary<string, string> ExtendedArabic = new()
    {
        ["TabEditor"] = "تحرير PDF",
        ["TabCompress"] = "ضغط",
        ["TabMerge"] = "دمج PDF",
        ["TabTools"] = "أدوات",
        ["TabPdfToWord"] = "PDF إلى Word",
        ["EditorHint"] = "افتح PDF لتحرير الصفحات وإضافة نص وصور وتوقيع واختام وأشكال. اسحب الصفحات لإعادة الترتيب. تراجع/إعادة. احفظ مع ضغط اختياري.",
        ["EditorUndo"] = "تراجع",
        ["EditorRedo"] = "إعادة",
        ["EditorPagesDragHint"] = "اسحب الصفحات لإعادة الترتيب",
        ["EditorToolSignature"] = "توقيع",
        ["EditorToolStamp"] = "ختم",
        ["EditorToolWhiteout"] = "تغطية",
        ["EditorStampPrompt"] = "أدخل نص الختم (مثل: معتمد):",
        ["EditorStampFont"] = "الخط والنمط",
        ["EditorRotateSelection"] = "اسحب للتدوير",
        ["EditorPickColor"] = "اختيار لون...",
        ["EditorFormFields"] = "حقول النموذج",
        ["EditorNoFormFields"] = "لا توجد حقول نموذج في هذا PDF.",
        ["EditorFormValue"] = "قيمة الحقل",
        ["EditorApplyFormValue"] = "تطبيق القيمة",
        ["EditorSelectFormField"] = "اختر حقل نموذج أولاً.",
        ["EditorFormReadOnly"] = "حقل النموذج للقراءة فقط.",
        ["EditorFormApplied"] = "تم تحديث حقل النموذج: {0}",
        ["EditorDeleteFormField"] = "حذف الحقل",
        ["EditorEditFormField"] = "تعديل الحقل",
        ["EditorDeleteFormFieldConfirm"] = "حذف حقل النموذج \"{0}\" من هذا PDF؟",
        ["EditorFormFieldDeleted"] = "تم حذف حقل النموذج: {0}",
        ["CompressMode"] = "الوضع",
        ["CompressModeSingle"] = "ملف PDF واحد",
        ["CompressModeBatch"] = "مجلد دفعة",
        ["CompressBatchFolder"] = "مجلد الإدخال (ملفات PDF)",
        ["CompressBatchButton"] = "ضغط كل ملفات PDF",
        ["CompressBatchDone"] = "تم ضغط {0} ملف PDF.",
        ["CompressSelectBatchFolder"] = "يرجى اختيار مجلد يحتوي PDF.",
        ["CompressGhostscriptReady"] = "Ghostscript متوفر — المستوى المرتفع/الأقصى يستخدم ضغطاً أقوى.",
        ["CompressGhostscriptMissing"] = "Ghostscript غير موجود. شغّل setup-tools.bat للضغط الأقوى.",
        ["ToolsSource"] = "PDF المصدر",
        ["SplitHint"] = "قسّم PDF إلى عدة ملفات حسب الصفحة أو كل N صفحة أو عند أرقام محددة.",
        ["SplitMode"] = "وضع التقسيم",
        ["SplitModeEveryPage"] = "كل صفحة → PDF منفصل",
        ["SplitModeEveryN"] = "كل N صفحة",
        ["SplitModeAtPages"] = "تقسيم بعد أرقام صفحات",
        ["SplitParam"] = "المعامل",
        ["SplitParamEveryPage"] = "لا حاجة لمعامل",
        ["SplitParamEveryN"] = "صفحات لكل ملف، مثل 5",
        ["SplitParamAtPages"] = "أرقام صفحات مفصولة بفواصل، مثل 3, 7, 12",
        ["SplitButton"] = "تقسيم PDF",
        ["SplitProcessing"] = "جاري التقسيم...",
        ["SplitDone"] = "تم إنشاء {0} ملف PDF.",
        ["SplitFailed"] = "فشل التقسيم",
        ["SplitInvalidParam"] = "معامل تقسيم غير صالح.",
        ["ExtractHint"] = "استخرج نطاق صفحات من PDF إلى ملف جديد. استخدم 1-5 أو رقم صفحة واحد.",
        ["ExtractRange"] = "نطاق الصفحات",
        ["ExtractOutputName"] = "ملف الإخراج",
        ["ExtractButton"] = "استخراج صفحات",
        ["ExtractProcessing"] = "جاري الاستخراج...",
        ["ExtractDone"] = "تم الاستخراج إلى {0}",
        ["ExtractFailed"] = "فشل الاستخراج",
        ["ExtractInvalidRange"] = "أدخل نطاق صفحات صالح (مثل 1-5 أو 3).",
        ["ExtractSelectOutput"] = "يرجى اختيار ملف الإخراج.",
        ["WatermarkHint"] = "طبّق علامة مائية نصية على كل صفحة في PDF.",
        ["WatermarkText"] = "نص العلامة المائية",
        ["WatermarkDiagonal"] = "علامة مائية مائلة",
        ["WatermarkButton"] = "تطبيق العلامة المائية",
        ["WatermarkProcessing"] = "جاري تطبيق العلامة المائية...",
        ["WatermarkDone"] = "تم حفظ PDF مع العلامة المائية في {0}",
        ["WatermarkFailed"] = "فشلت العلامة المائية",
        ["WatermarkEnterText"] = "أدخل نص العلامة المائية.",
        ["ImagesToPdfHint"] = "أنشئ PDF جديداً من صورة أو أكثر. كل صورة تصبح صفحة واحدة مع ملاءمة الحجم.",
        ["ImagesToPdfSource"] = "الصور",
        ["ImagesToPdfBrowse"] = "استعراض الصور...",
        ["ImagesToPdfOutput"] = "PDF الناتج",
        ["ImagesToPdfButton"] = "إنشاء PDF من الصور",
        ["ImagesToPdfProcessing"] = "جاري إنشاء PDF من الصور...",
        ["ImagesToPdfDone"] = "تم إنشاء PDF بعدد {0} صفحة: {1}",
        ["ImagesToPdfFailed"] = "تعذر إنشاء PDF من الصور.",
        ["ImagesToPdfSelectImages"] = "اختر ملف صورة واحد على الأقل.",
        ["PdfToWordHint"] = "حوّل PDF إلى ملف Word (.docx) قابل للتحرير. مع الحفاظ على التخطيط، يُحافظ على موضع النص والتباعد وحجم الخط والصور قدر الإمكان. التصاميم المعقدة قد تختلف قليلاً.",
        ["PdfToWordPreserveLayout"] = "الحفاظ على التخطيط والتنسيق",
        ["PdfToWordOutput"] = "ملف Word الناتج",
        ["PdfToWordFilter"] = "مستندات Word|*.docx",
        ["PdfToWordButton"] = "تحويل إلى Word",
        ["PdfToWordProcessing"] = "جاري التحويل إلى Word...",
        ["PdfToWordProgress"] = "جاري تحويل الصفحة {0}...",
        ["PdfToWordDone"] = "تم تحويل {0} صفحة إلى {1}",
        ["PdfToWordFailed"] = "فشل تحويل PDF إلى Word.",
        ["PdfToWordSelectOutput"] = "يرجى اختيار ملف .docx للإخراج.",
        ["ExtractRangeExample"] = "1-",
        ["AboutDescription"] = "محرر PDF وضاغط ودمج وأدوات حديث لنظام Windows.",
        ["AboutFeatures"] = "• تحرير PDF — صفحات، نص، صور، توقيع، نماذج، تراجع/إعادة\n• ضغط — ملف واحد أو دفعة، Ghostscript للجودة القصوى\n• دمج — إعادة ترتيب PDF قبل الدمج\n• أدوات — تقسيم، استخراج، علامة مائية، صور إلى PDF\n• PDF إلى Word — استخراج النص إلى .docx\n• ثيم فاتح/داكن · 8 لغات · عربي RTL",
        ["EditorOpen"] = "فتح PDF",
        ["EditorNewPdf"] = "PDF جديد",
        ["EditorNewCreated"] = "PDF فارغ جديد — {0} صفحة.",
        ["EditorClose"] = "إغلاق PDF",
        ["EditorClosed"] = "تم إغلاق PDF",
        ["EditorSave"] = "حفظ PDF",
        ["EditorSaveAs"] = "حفظ باسم...",
        ["EditorNoDocument"] = "لم يُحمّل أي PDF. انقر فتح PDF أو أسقط ملفاً هنا.",
        ["EditorPages"] = "الصفحات",
        ["EditorPagePreview"] = "معاينة الصفحة",
        ["EditorToolSelect"] = "تحديد",
        ["EditorToolEditText"] = "تحرير النص",
        ["EditorDeleteSelection"] = "حذف التحديد",
        ["EditorSelectHint"] = "أداة التحديد: انقر للتحديد، اسحب للنقل، المقابض للتغيير، النقطة العلوية للتدوير. انقر مرتين على النص/الأختام لتعديل الخط والنمط.",
        ["EditorTransformHint"] = "اسحب زوايا المقابض لتغيير الحجم. اسحب النقطة العلوية للتدوير. انقر مرتين على الختم لتغيير الخط والحجم والنمط.",
        ["EditorEditTextHint"] = "تحرير النص: المربعات الزرقاء نص، البرتقالية صور/أيقونات. انقر للتحديد، اسحب للنقل، انقر مرتين على النص. استخدم اللوحة لتغيير الحجم واللون والنمط. احفظ PDF للتطبيق.",
        ["EditorContentEditTitle"] = "تحرير التحديد",
        ["EditorBlockText"] = "النص",
        ["EditorBlockFontSize"] = "حجم الخط",
        ["EditorBlockColor"] = "اللون",
        ["EditorContentEditHint"] = "اسحب للنقل. الحذف يزيل الكتلة. احفظ PDF للتطبيق.",
        ["EditorImageSelected"] = "تم تحديد صورة أو أيقونة — اسحب للنقل أو احذف.",
        ["EditorRotateStamp"] = "تدوير الختم",
        ["EditorSignatureTitle"] = "إنشاء توقيع",
        ["EditorSignatureDrawTab"] = "رسم",
        ["EditorSignatureTypeTab"] = "كتابة",
        ["EditorSignatureUploadTab"] = "رفع",
        ["EditorSignatureDrawHint"] = "ارسم توقيعك بالماوس أو القلم.",
        ["EditorSignatureTypeHint"] = "اكتب اسمك واختر الخط والحجم واللون والنمط.",
        ["EditorSignatureUploadHint"] = "ارفع صورة لتوقيعك.",
        ["EditorSignatureBrowse"] = "استعراض صورة...",
        ["EditorSignatureClear"] = "مسح",
        ["EditorSignatureDefaultName"] = "اسمك",
        ["EditorSignatureReady"] = "التوقيع جاهز — انقر على الصفحة لوضعه.",
        ["Create"] = "إنشاء",
        ["EditorToolText"] = "إضافة نص",
        ["EditorToolImage"] = "إضافة صورة",
        ["EditorToolRectangle"] = "مستطيل",
        ["EditorToolEllipse"] = "بيضاوي",
        ["EditorToolLine"] = "خط",
        ["EditorAddTextField"] = "إضافة حقل نص",
        ["EditorAddComboField"] = "إضافة قائمة منسدلة",
        ["EditorFormFieldName"] = "اسم الحقل",
        ["EditorFormDefaultValue"] = "القيمة الافتراضية",
        ["EditorComboOptions"] = "الخيارات (سطر لكل خيار)",
        ["EditorTextFieldPrompt"] = "أدخل اسم الحقل ونمط النص والقيمة الافتراضية، ثم ارسم الحقل على الصفحة.",
        ["EditorComboFieldPrompt"] = "أدخل اسم الحقل والخيارات والقيمة الافتراضية، ثم ارسم الحقل على الصفحة.",
        ["EditorDrawFormFieldHint"] = "اسحب على الصفحة لرسم منطقة الحقل.",
        ["EditorPendingFormFieldHint"] = "ضع \"{0}\" على الصفحة: انقر واسحب على معاينة PDF. سيظهر في القائمة بعد وضعه.",
        ["EditorFormFontFamily"] = "نوع الخط",
        ["EditorFormRotation"] = "التدوير",
        ["EditorFormPreview"] = "معاينة",
        ["EditorFormFieldAdded"] = "تمت إضافة حقل النموذج: {0}",
        ["EditorColorHex"] = "Hex",
        ["EditorToolHighlight"] = "تمييز",
        ["EditorRotateLeft"] = "تدوير يسار",
        ["EditorRotateRight"] = "تدوير يمين",
        ["EditorAddPage"] = "إضافة صفحة",
        ["EditorPageAdded"] = "تمت إضافة صفحة فارغة {0}.",
        ["EditorCannotDeleteLastPage"] = "لا يمكن حذف الصفحة الوحيدة في المستند.",
        ["EditorDeletePage"] = "حذف صفحة",
        ["EditorMoveUp"] = "تحريك لأعلى",
        ["EditorMoveDown"] = "تحريك لأسفل",
        ["EditorZoomIn"] = "تكبير",
        ["EditorZoomOut"] = "تصغير",
        ["EditorTextPrompt"] = "أدخل النص لوضعه على الصفحة:",
        ["EditorAddTextPrompt"] = "أدخل النص واختر الخط واللون والتدوير، ثم انقر على الصفحة لوضعه.",
        ["EditorAddTextReady"] = "النص \"{0}\" جاهز — انقر على الصفحة لوضعه.",
        ["EditorAddTextPreviewDefault"] = "نص تجريبي",
        ["EditorImageFilter"] = "ملفات صور|*.png;*.jpg;*.jpeg;*.bmp;*.gif;*.webp|كل الملفات|*.*",
        ["EditorOpenFilter"] = "ملفات PDF|*.pdf|كل الملفات|*.*",
        ["EditorSaveFilter"] = "ملفات PDF|*.pdf",
        ["EditorCompressOnSave"] = "ضغط عند الحفظ",
        ["EditorLoaded"] = "تم تحميل {0} — {1} صفحة",
        ["EditorSaved"] = "تم الحفظ في {0}",
        ["EditorSelectPage"] = "اختر صفحة أولاً.",
        ["EditorDropHint"] = "أسقط ملف PDF هنا",
        ["CompressHint"] = "قلّل حجم PDF مع الحفاظ على جودة مقروءة. اختر مستوى ومجلد الإخراج.",
        ["CompressSource"] = "PDF المصدر",
        ["CompressOutput"] = "مجلد الإخراج",
        ["CompressLevel"] = "مستوى الضغط",
        ["CompressLevelLow"] = "منخفض — أسرع، تقليل أقل",
        ["CompressLevelMedium"] = "متوسط — متوازن",
        ["CompressLevelHigh"] = "مرتفع — ملفات أصغر",
        ["CompressLevelMaximum"] = "أقصى — أصغر حجم",
        ["CompressButton"] = "ضغط PDF",
        ["CompressReady"] = "جاهز",
        ["CompressProcessing"] = "جاري الضغط...",
        ["CompressDone"] = "اكتمل — تم حفظ {0} ({1} → {2})",
        ["CompressFailed"] = "فشل الضغط",
        ["CompressSelectFile"] = "يرجى اختيار ملف PDF.",
        ["CompressSelectOutput"] = "يرجى اختيار مجلد الإخراج.",
        ["MergeHint"] = "أضف عدة ملفات PDF واسحب أو استخدم الأسهم لترتيب الدمج. الملف الأول في القائمة يصبح أول الصفحات في الناتج.",
        ["MergeAddFiles"] = "إضافة PDF",
        ["MergeRemove"] = "إزالة",
        ["MergeMoveUp"] = "تحريك لأعلى",
        ["MergeMoveDown"] = "تحريك لأسفل",
        ["MergeClear"] = "مسح القائمة",
        ["MergeOutputName"] = "اسم ملف الإخراج",
        ["MergeOutputFolder"] = "مجلد الإخراج",
        ["MergeButton"] = "دمج PDF",
        ["MergeReady"] = "جاهز",
        ["MergeProcessing"] = "جاري الدمج...",
        ["MergeDone"] = "تم دمج {0} ملف(ات) → {1}",
        ["MergeFailed"] = "فشل الدمج",
        ["MergeNeedTwo"] = "أضف ملف PDF واحداً على الأقل.",
        ["MergeSelectOutput"] = "يرجى اختيار مجلد الإخراج.",
        ["About"] = "حول",
        ["AboutVersion"] = "الإصدار",
        ["AboutAuthorPrefix"] = "حقوق النشر © 2026 ",
        ["AboutDescription"] = "محرر PDF وضاغط ودمج حديث لنظام Windows.",
        ["AboutFeatures"] = "• تحرير PDF — صفحات، نص، صور، أشكال، تمييز\n• ضغط — إعدادات جودة لملفات أصغر\n• دمج — إعادة ترتيب PDF قبل الدمج\n• ثيم فاتح/داكن · 8 لغات · عربي RTL",
        ["AboutClose"] = "إغلاق",
        ["Ok"] = "موافق",
    };

    private static readonly Dictionary<AppLanguage, Dictionary<string, string>> Strings = CreateStrings();

    public AppLanguage Current { get; private set; } = AppLanguage.English;

    public string Get(string key) =>
        Strings.TryGetValue(Current, out var lang) && lang.TryGetValue(key, out var value)
            ? value
            : Strings[AppLanguage.English].GetValueOrDefault(key, key);

    public void SetLanguage(AppLanguage language) => Current = language;

    public bool IsRtl => Current == AppLanguage.Arabic;

    public static string GetNativeLanguageName(AppLanguage language) => language switch
    {
        AppLanguage.English => "English",
        AppLanguage.Arabic => "العربية",
        AppLanguage.Spanish => "Español",
        AppLanguage.French => "Français",
        AppLanguage.German => "Deutsch",
        AppLanguage.Chinese => "中文",
        AppLanguage.Swedish => "Svenska",
        AppLanguage.Norwegian => "Norsk",
        _ => language.ToString()
    };

    public static IReadOnlyList<AppLanguage> SupportedLanguages { get; } =
        Enum.GetValues<AppLanguage>().Cast<AppLanguage>().ToList();

    private static Dictionary<AppLanguage, Dictionary<string, string>> CreateStrings()
    {
        var map = BuildStrings();
        ApplyExtended(map[AppLanguage.English], ExtendedEnglish);
        ApplyExtended(map[AppLanguage.Arabic], ExtendedArabic);
        foreach (var lang in map.Keys.Where(k => k is not AppLanguage.English and not AppLanguage.Arabic))
            ApplyExtended(map[lang], ExtendedEnglish);
        return map;
    }

    private static Dictionary<AppLanguage, Dictionary<string, string>> BuildStrings() => new()
    {
        [AppLanguage.English] = Dict(
            "PDFMaster", "Modern PDF editor, compressor, merge, and tools suite",
            "Save", "Cancel", "Reset defaults", "General", "Appearance", "Language",
            "Default save folder", "Theme", "Dark", "Light", "Settings", "Browse",
            "Ready", "Open folder"),

        [AppLanguage.Arabic] = Dict(
            "PDF ماستر", "محرر PDF وضاغط ودمج حديث",
            "حفظ", "إلغاء", "إعادة الافتراضي", "عام", "المظهر", "اللغة",
            "مجلد الحفظ الافتراضي", "المظهر", "داكن", "فاتح", "الإعدادات", "استعراض",
            "جاهز", "فتح المجلد"),

        [AppLanguage.Spanish] = Dict(
            "PDFMaster", "Editor, compresor y fusionador de PDF moderno",
            "Guardar", "Cancelar", "Restablecer", "General", "Apariencia", "Idioma",
            "Carpeta de guardado", "Tema", "Oscuro", "Claro", "Ajustes", "Examinar",
            "Listo", "Abrir carpeta"),

        [AppLanguage.French] = Dict(
            "PDFMaster", "Éditeur, compresseur et fusionneur PDF moderne",
            "Enregistrer", "Annuler", "Réinitialiser", "Général", "Apparence", "Langue",
            "Dossier de sauvegarde", "Thème", "Sombre", "Clair", "Paramètres", "Parcourir",
            "Prêt", "Ouvrir le dossier"),

        [AppLanguage.German] = Dict(
            "PDFMaster", "Moderner PDF-Editor, Kompressor und Merge-Tool",
            "Speichern", "Abbrechen", "Zurücksetzen", "Allgemein", "Darstellung", "Sprache",
            "Speicherordner", "Design", "Dunkel", "Hell", "Einstellungen", "Durchsuchen",
            "Bereit", "Ordner öffnen"),

        [AppLanguage.Chinese] = Dict(
            "PDFMaster", "现代 PDF 编辑、压缩与合并工具",
            "保存", "取消", "恢复默认", "常规", "外观", "语言",
            "默认保存文件夹", "主题", "深色", "浅色", "设置", "浏览",
            "就绪", "打开文件夹"),

        [AppLanguage.Swedish] = Dict(
            "PDFMaster", "Modern PDF-redigerare, kompressor och sammanslagning",
            "Spara", "Avbryt", "Återställ standard", "Allmänt", "Utseende", "Språk",
            "Standardmapp", "Tema", "Mörkt", "Ljust", "Inställningar", "Bläddra",
            "Klar", "Öppna mapp"),

        [AppLanguage.Norwegian] = Dict(
            "PDFMaster", "Moderne PDF-redigerer, kompressor og sammenslåing",
            "Lagre", "Avbryt", "Tilbakestill standard", "Generelt", "Utseende", "Språk",
            "Standardmappe", "Tema", "Mørk", "Lys", "Innstillinger", "Bla gjennom",
            "Klar", "Åpne mappe"),
    };

    private static Dictionary<string, string> Dict(
        string appTitle, string appSubtitle,
        string save, string cancel, string reset, string general, string appearance, string language,
        string savePath, string theme, string themeDark, string themeLight, string settings, string browse,
        string ready, string openFolder) => new()
    {
        ["AppTitle"] = appTitle,
        ["AppSubtitle"] = appSubtitle,
        ["Save"] = save,
        ["Cancel"] = cancel,
        ["Reset"] = reset,
        ["General"] = general,
        ["Appearance"] = appearance,
        ["Language"] = language,
        ["SavePath"] = savePath,
        ["Theme"] = theme,
        ["ThemeDark"] = themeDark,
        ["ThemeLight"] = themeLight,
        ["Settings"] = settings,
        ["Browse"] = browse,
        ["Ready"] = ready,
        ["OpenFolder"] = openFolder,
    };

    private static void ApplyExtended(Dictionary<string, string> target, Dictionary<string, string> extra)
    {
        foreach (var (key, value) in extra)
            target[key] = value;
    }
}
